### ISSUE TITLE
UnboundLocalError: local variable 'info' referenced before assignment

### ISSUE THREAD

**Issue by ReidandKat** [mdhiggins/radarr-sma#2]
autoProcess.ini:
```
[SickBeard]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Sonarr]
host = redacted
port = 8989
web_root = 
ssl = False
apikey = redacted

[Radarr]
host = redacted
port = 7878
web_root = 
ssl = False
apikey = redacted

[MP4]
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 5000
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = ac3
ignore-trudhd = true
audio-language = 
audio-default-language = 
audio-channel-bitrate = 256
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0644
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
web_root = 
ssl = False
apikey = 
delay = 65
method = renamer
delete_failed = False

[uTorrent]
convert = 
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sonarr-label = sonarr
bypass-label = bypass
sickrage-label = sickrage
webui = False
action_before = stop
action_after = removedata
host = http://localhost:8080/
username = 
password = 
output_directory = 
radarr-label = radarr

[Deluge]
host = localhost
username = localclient
convert = True
password = redacted
sonarr-label = tv-sonarr
bypass-label = bypass
sickbeard-label = sickbeard
port = 58846
sickrage-label = sickrage
couchpotato-label = couchpotato
output_directory = 
remove = false
radarr-label = radarr

[SABNZBD]
convert = True
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
couchpotato-category = couchpotato
sickbeard-category = sickbeard
output_directory = 

[Sickrage]
host = localhost
port = 8081
username = 
password = 
web_root = 
ssl = False
api_key = 

[Plex]
host = localhost
port = 32400
refresh = True
token = 
```

Error:
```
19-6-1 12:51:44.5|Error|python3|Traceback (most recent call last):
19-6-1 12:51:44.5|Error|python3|  File "/usr/local/bin/sma/sickbeard_mp4_automator/postRadarr.py", line 51, in <module>
19-6-1 12:51:44.5|Error|python3|    output = converter.process(inputfile, original=original)
19-6-1 12:51:44.5|Error|python3|  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 238, in process
19-6-1 12:51:44.5|Error|python3|    dim = self.getDimensions(outputfile)
19-6-1 12:51:44.5|Error|python3|  File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 282, in getDimensions
19-6-1 12:51:44.5|Error|python3|    self.log.debug("Height: %s" % info.video.video_height)
19-6-1 12:51:44.5|Error|python3|UnboundLocalError: local variable 'info' referenced before assignment
```

**Comment by ReidandKat** [comment]
Should I have completed download handling on or off while using this?

**Comment by ReidandKat** [comment]
Seems to be working now, not sure what changed
